// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

type Polltype struct {
	ID   []byte
	Name string
}

type Subject struct {
	ID   []byte
	Name string
}

type SubjectPolltype struct {
	SubjectID  []byte
	PolltypeID []byte
}
