// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
)

const createPollType = `-- name: CreatePollType :one
insert into
polltype (
	id, name
) values (
	?, ?
) returning id, name
`

type CreatePollTypeParams struct {
	ID   []byte
	Name string
}

func (q *Queries) CreatePollType(ctx context.Context, arg CreatePollTypeParams) (Polltype, error) {
	row := q.db.QueryRowContext(ctx, createPollType, arg.ID, arg.Name)
	var i Polltype
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createSubject = `-- name: CreateSubject :one
insert into
subject (
	id, name
) values (
	?, ?
) returning id, name
`

type CreateSubjectParams struct {
	ID   []byte
	Name string
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRowContext(ctx, createSubject, arg.ID, arg.Name)
	var i Subject
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createSubjectPollType = `-- name: CreateSubjectPollType :one
insert into
subject_polltype (
	subject_id, polltype_id
) values (
	?, ?
) returning subject_id, polltype_id
`

type CreateSubjectPollTypeParams struct {
	SubjectID  []byte
	PolltypeID []byte
}

func (q *Queries) CreateSubjectPollType(ctx context.Context, arg CreateSubjectPollTypeParams) (SubjectPolltype, error) {
	row := q.db.QueryRowContext(ctx, createSubjectPollType, arg.SubjectID, arg.PolltypeID)
	var i SubjectPolltype
	err := row.Scan(&i.SubjectID, &i.PolltypeID)
	return i, err
}

const listPollTypes = `-- name: ListPollTypes :many
select
	id, name
from
	polltype
order by
	name
`

func (q *Queries) ListPollTypes(ctx context.Context) ([]Polltype, error) {
	rows, err := q.db.QueryContext(ctx, listPollTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Polltype
	for rows.Next() {
		var i Polltype
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPollType = `-- name: SearchPollType :one
select
	id, name
from
	polltype
where
	name = ?
`

func (q *Queries) SearchPollType(ctx context.Context, name string) (Polltype, error) {
	row := q.db.QueryRowContext(ctx, searchPollType, name)
	var i Polltype
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
