// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const createPoll = `-- name: CreatePoll :one
insert into
poll (
	id, votehub_id,
	poll_type, sample_size,
	population, url,
	created_at, start_date,
	end_date, pollster_id,
	seat_name, internal,
	partisan, subject_id
) values (
	?, ?,
	?, ?,
	?, ?,
	?, ?,
	?, ?,
	?, ?,
	?, ?
) returning id, votehub_id, poll_type, sample_size, population, url, created_at, start_date, end_date, pollster_id, seat_name, internal, partisan, subject_id
`

type CreatePollParams struct {
	ID         []byte
	VotehubID  string
	PollType   string
	SampleSize sql.NullInt64
	Population sql.NullString
	Url        string
	CreatedAt  string
	StartDate  string
	EndDate    string
	PollsterID []byte
	SeatName   sql.NullString
	Internal   int64
	Partisan   sql.NullString
	SubjectID  []byte
}

func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) (Poll, error) {
	row := q.db.QueryRowContext(ctx, createPoll,
		arg.ID,
		arg.VotehubID,
		arg.PollType,
		arg.SampleSize,
		arg.Population,
		arg.Url,
		arg.CreatedAt,
		arg.StartDate,
		arg.EndDate,
		arg.PollsterID,
		arg.SeatName,
		arg.Internal,
		arg.Partisan,
		arg.SubjectID,
	)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.VotehubID,
		&i.PollType,
		&i.SampleSize,
		&i.Population,
		&i.Url,
		&i.CreatedAt,
		&i.StartDate,
		&i.EndDate,
		&i.PollsterID,
		&i.SeatName,
		&i.Internal,
		&i.Partisan,
		&i.SubjectID,
	)
	return i, err
}

const createPollType = `-- name: CreatePollType :one
insert into
polltype (
	id, name
) values (
	?, ?
) returning id, name
`

type CreatePollTypeParams struct {
	ID   []byte
	Name string
}

func (q *Queries) CreatePollType(ctx context.Context, arg CreatePollTypeParams) (Polltype, error) {
	row := q.db.QueryRowContext(ctx, createPollType, arg.ID, arg.Name)
	var i Polltype
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createPollster = `-- name: CreatePollster :one
insert into
pollster (
	id, name
) values (
	?, ?
) returning id, name
`

type CreatePollsterParams struct {
	ID   []byte
	Name string
}

func (q *Queries) CreatePollster(ctx context.Context, arg CreatePollsterParams) (Pollster, error) {
	row := q.db.QueryRowContext(ctx, createPollster, arg.ID, arg.Name)
	var i Pollster
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createSubject = `-- name: CreateSubject :one
insert into
subject (
	id, name
) values (
	?, ?
) returning id, name
`

type CreateSubjectParams struct {
	ID   []byte
	Name string
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRowContext(ctx, createSubject, arg.ID, arg.Name)
	var i Subject
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createSubjectPollType = `-- name: CreateSubjectPollType :one
insert into
subject_polltype (
	subject_id, polltype_id
) values (
	?, ?
) returning subject_id, polltype_id
`

type CreateSubjectPollTypeParams struct {
	SubjectID  []byte
	PolltypeID []byte
}

func (q *Queries) CreateSubjectPollType(ctx context.Context, arg CreateSubjectPollTypeParams) (SubjectPolltype, error) {
	row := q.db.QueryRowContext(ctx, createSubjectPollType, arg.SubjectID, arg.PolltypeID)
	var i SubjectPolltype
	err := row.Scan(&i.SubjectID, &i.PolltypeID)
	return i, err
}

const listPollTypes = `-- name: ListPollTypes :many
select
	id, name
from
	polltype
order by
	name
`

func (q *Queries) ListPollTypes(ctx context.Context) ([]Polltype, error) {
	rows, err := q.db.QueryContext(ctx, listPollTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Polltype
	for rows.Next() {
		var i Polltype
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPollsters = `-- name: ListPollsters :many
select
	id, name
from
	pollster
order by
	name
`

func (q *Queries) ListPollsters(ctx context.Context) ([]Pollster, error) {
	rows, err := q.db.QueryContext(ctx, listPollsters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pollster
	for rows.Next() {
		var i Pollster
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPollType = `-- name: SearchPollType :one
select
	id, name
from
	polltype
where
	name = ?
`

func (q *Queries) SearchPollType(ctx context.Context, name string) (Polltype, error) {
	row := q.db.QueryRowContext(ctx, searchPollType, name)
	var i Polltype
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const searchPollster = `-- name: SearchPollster :one
select
	id, name
from
	pollster
where
	name = ?
`

func (q *Queries) SearchPollster(ctx context.Context, name string) (Pollster, error) {
	row := q.db.QueryRowContext(ctx, searchPollster, name)
	var i Pollster
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const searchSubject = `-- name: SearchSubject :one
select
	id, name
from
	subject
where
	name = ?
`

func (q *Queries) SearchSubject(ctx context.Context, name string) (Subject, error) {
	row := q.db.QueryRowContext(ctx, searchSubject, name)
	var i Subject
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
