// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
)

const createPollType = `-- name: CreatePollType :one
insert into
polltype (
	id, name
) values (
	?, ?
)
returning
	id, name
`

type CreatePollTypeParams struct {
	ID   []byte
	Name string
}

func (q *Queries) CreatePollType(ctx context.Context, arg CreatePollTypeParams) (Polltype, error) {
	row := q.db.QueryRowContext(ctx, createPollType, arg.ID, arg.Name)
	var i Polltype
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listPollTypes = `-- name: ListPollTypes :many
select
	id, name
from
	polltype
order by
	name
`

func (q *Queries) ListPollTypes(ctx context.Context) ([]Polltype, error) {
	rows, err := q.db.QueryContext(ctx, listPollTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Polltype
	for rows.Next() {
		var i Polltype
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
